apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNE1Ea3lOakU1TlRVeU5sb1hEVEk0TURreU16RTVOVFV5Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUGsyCnJHNDBJQ0FqWGZ4TUljM1FLUnNRSER2dS96Wi84aFFxRjRLUXZJMXczRy9reVQ0NVY5dU56NTd3R3dVMGl4bVIKYTdiRXRCdWpFbWo4azhEdUsyQnBWTXJBUVVKY2RHWld1VlNtUjhEWTh0a0dvNWN1TEJDTlhkR3gvSjN1YVJMQgp1L3lIOGI4OG8yYlRUU3Z6NGgvU3A1bGhYa3JPZEJRWGV2S3lmbnJEU3VUTUtBd1RzcjBudlJ6bTFjSXNpQnF6CmMxeFdVeVRKQVZabkRkN092MW5WeC9UcmVNNktoOXpxZmhYWFNCOWdaM1hmNU5pbkNFU2o0VzZrMXZwSkRrdi8KOFhEcytKVXJoZUpQZlhXMElBTS9kUlFHS2dsNURITUJkbXdheE04amZZeEk0OWRUTUtBWnh2UkZwbkE3M3FjUgpUWC9LTElzOElITEptN3IwZE1rQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBaGhNS1h4RlB5WXhKRzBzaGh4L21EdVZBS0sKaENWY2ZqNUMzd2hOeWExUmJLWnM5L1ZBOHQ2OHZYdkxqWnUzVHNldnRwRTUvTytTQm5lU3E3dldrQUpnR1hDUApuSEc4S0YwRDltbFJCMUdsY1E4bmVidjdNK0lBNGZibWFhQ09CN0VCK04vVklIRExVcm1sQy9JNkpTQ1BtOWg2CnFwa2JYZUV3MmJVaDNZM2tmYWxqTnplKzlHcXJtWEdTQkt6UWFxN0U4emxTKzR5cUk3bU9lTlZ2ZGpVKzRxUFMKbDdHRzZmeUVSeC9HMzFqQ1lNZGdqWGpERXo0SWJnd2c2c09iZFN1WEFZMWZOVUpEQkVjZGpJSmdEaktVQmZmaQphcTVJQWVoMEJOSy9XRFRLQ1pjUFNxS0FKdFlwVTZoVUNRTTVISXU1aXNYZjhjQmR3YktTMVc4SUpZcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://ACFDFE59EC3C97C73E1B1BC72AD62F47.sk1.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:899826514230:cluster/test
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:899826514230:cluster/test
    user: arn:aws:eks:us-west-2:899826514230:cluster/test
  name: arn:aws:eks:us-west-2:899826514230:cluster/test
current-context: arn:aws:eks:us-west-2:899826514230:cluster/test
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:899826514230:cluster/test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - test
      command: aws-iam-authenticator
